version: "3.3"
services:
  app:
    build: ./app
    command: nodemon yarn start
    container_name: app_1
    ports:
      - "3000:3000"
    networks:
      - react-test
    volumes:
      - './app:/app'
      - /app/node_modules
    depends_on:
      - api

  api:
    build: ./api
    command: nodemon yarn start
    container_name: api_1
    ports:
      - "5000:5000"
    networks:
      - react-test
    volumes:
      - './api:/app'
      - /app/node_modules

networks:
  react-test:   